#!/usr/bin/env python3
"""
CS2 Gap Analyzer - Generate highlights for review
"""
import sys
import json
from pathlib import Path
from typing import Dict, Any, List

from src.parser import DemoParser
from src.analyzer import GapAnalyzer
from src.highlights import HighlightsAnalyzer


def generate_review_file(highlights: List[Dict[str, Any]], output_path: str):
    """Generate human-readable review file with timestamps"""
    lines = []
    
    # Header
    lines.append("=" * 80)
    lines.append("🎬 CS2 HIGHLIGHTS - MOMENTS CLÉS À REVOIR")
    lines.append("=" * 80)
    lines.append("")
    lines.append("💡 INSTRUCTIONS:")
    lines.append("  1. Ouvrir CS2 et charger la démo")
    lines.append("  2. Appuyer sur Shift+F2 pour ouvrir le panneau de contrôle")
    lines.append("  3. Utiliser les commandes ci-dessous pour sauter aux moments clés")
    lines.append("  4. Ou utiliser le script highlights.cfg pour navigation automatique")
    lines.append("")
    lines.append("=" * 80)
    lines.append("")
    
    if not highlights:
        lines.append("✨ Aucun moment critique détecté ! Bon niveau général.")
        lines.append("")
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write("\n".join(lines))
        return
    
    # Group by priority
    critical = [h for h in highlights if h['priority'] >= 80]
    important = [h for h in highlights if 60 <= h['priority'] < 80]
    moderate = [h for h in highlights if 40 <= h['priority'] < 60]
    learning = [h for h in highlights if h['priority'] < 40]
    
    # Critical moments
    if critical:
        lines.append("🔴 MOMENTS CRITIQUES (À REVOIR EN PRIORITÉ)")
        lines.append("-" * 80)
        lines.append("")
        for i, highlight in enumerate(critical, 1):
            lines.extend(_format_highlight(i, highlight))
            lines.append("")
    
    # Important moments
    if important:
        lines.append("🟡 MOMENTS IMPORTANTS")
        lines.append("-" * 80)
        lines.append("")
        for i, highlight in enumerate(important, len(critical) + 1):
            lines.extend(_format_highlight(i, highlight))
            lines.append("")
    
    # Moderate moments
    if moderate:
        lines.append("🟢 POINTS D'AMÉLIORATION")
        lines.append("-" * 80)
        lines.append("")
        for i, highlight in enumerate(moderate, len(critical) + len(important) + 1):
            lines.extend(_format_highlight(i, highlight))
            lines.append("")
    
    # Learning moments
    if learning:
        lines.append("✅ EXEMPLES POSITIFS (À ÉTUDIER)")
        lines.append("-" * 80)
        lines.append("")
        for i, highlight in enumerate(learning, len(critical) + len(important) + len(moderate) + 1):
            lines.extend(_format_highlight(i, highlight))
            lines.append("")
    
    # Footer
    lines.append("=" * 80)
    lines.append(f"📊 TOTAL: {len(highlights)} moments identifiés")
    lines.append("💡 TIP: Commencer par les moments critiques (🔴) pour impact maximal")
    lines.append("=" * 80)
    lines.append("")
    
    # Write to file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines))


def _format_highlight(num: int, highlight: Dict[str, Any]) -> List[str]:
    """Format a single highlight entry"""
    lines = []
    
    category = highlight['category']
    tick = highlight['tick']
    round_num = highlight['round']
    time = highlight['time']
    description = highlight['description']
    attacker = highlight['attacker']
    weapon = highlight['weapon']
    context = highlight.get('context', '')
    economic_impact = highlight.get('economic_impact', 0)
    
    lines.append(f"{num}. {category}")
    lines.append(f"   Round {round_num} - {time}")
    lines.append(f"   {description}")
    if attacker != 'YOU':
        lines.append(f"   vs {attacker} ({weapon})")
    else:
        lines.append(f"   Arme: {weapon}")
    if context:
        lines.append(f"   {context}")
    if economic_impact > 0:
        lines.append(f"   💰 Impact: {economic_impact}$")
    lines.append("")
    lines.append(f"   🎮 CS2 Command:")
    lines.append(f"      demo_gototick {tick}")
    lines.append(f"      demo_timescale 0.5  (pour ralenti)")
    lines.append("")
    lines.append(f"   ⏱️  Pour clip: Tick {tick - 200} à {tick + 200} (~6s avant/après)")
    
    return lines


def generate_cs2_script(highlights: List[Dict[str, Any]], output_path: str, demo_name: str):
    """Generate CS2 .cfg script for automatic navigation"""
    lines = []
    
    # Header comments
    lines.append("// CS2 Highlights Navigation Script")
    lines.append(f"// Demo: {demo_name}")
    lines.append("// Generated by CS2 Gap Analyzer")
    lines.append("//")
    lines.append("// USAGE:")
    lines.append("//   1. Place this file in: csgo/cfg/")
    lines.append("//   2. In CS2 console: playdemo <demoname>")
    lines.append("//   3. Press Shift+F2 to open demo controls")
    lines.append("//   4. In console: exec highlights")
    lines.append("//   5. Press F5 to jump to next highlight")
    lines.append("//   6. Press F6 to slow motion (0.5x)")
    lines.append("//   7. Press F7 to normal speed (1x)")
    lines.append("")
    
    # Setup commands
    lines.append("echo \"\"")
    lines.append("echo \"===========================================\"")
    lines.append("echo \"CS2 HIGHLIGHTS NAVIGATION\"")
    lines.append(f"echo \"Total highlights: {len(highlights)}\"")
    lines.append("echo \"===========================================\"")
    lines.append("echo \"F5 = Next highlight\"")
    lines.append("echo \"F6 = Slow motion (0.5x)\"")
    lines.append("echo \"F7 = Normal speed (1x)\"")
    lines.append("echo \"===========================================\"")
    lines.append("echo \"\"")
    lines.append("")
    
    # Speed controls
    lines.append("// Speed controls")
    lines.append("bind \"F6\" \"demo_timescale 0.5; echo Slow motion (0.5x)\"")
    lines.append("bind \"F7\" \"demo_timescale 1; echo Normal speed (1x)\"")
    lines.append("")
    
    # Navigation through highlights
    if highlights:
        lines.append("// Navigation aliases")
        
        for i, highlight in enumerate(highlights):
            alias_name = f"highlight_{i}"
            next_alias = f"highlight_{i+1}" if i < len(highlights) - 1 else "highlight_end"
            
            tick = highlight['tick']
            category = highlight['category']
            round_num = highlight['round']
            description = highlight['description']
            
            # Create alias for this highlight
            lines.append(f"alias {alias_name} \"demo_gototick {tick}; echo [{i+1}/{len(highlights)}] {category} - Round {round_num}; echo {description}; bind F5 {next_alias}\"")
        
        # End alias
        lines.append(f"alias highlight_end \"echo Fin des highlights ! Retour au début.; bind F5 highlight_0\"")
        lines.append("")
        
        # Initial binding
        lines.append("// Start navigation")
        lines.append("bind \"F5\" \"highlight_0\"")
        lines.append("")
        lines.append("// Jump to first highlight automatically")
        lines.append("highlight_0")
    else:
        lines.append("echo \"No highlights found.\"")
    
    # Write to file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines))


def main():
    """Main entry point"""
    if len(sys.argv) < 3:
        print("Usage: python generate_highlights.py <demo_path> <player_name> [output_dir]")
        sys.exit(1)
    
    demo_path = sys.argv[1]
    player_name = sys.argv[2]
    output_dir = sys.argv[3] if len(sys.argv) > 3 else "output"
    
    # Validate demo file
    if not Path(demo_path).exists():
        print(f"❌ Demo file not found: {demo_path}")
        sys.exit(1)
    
    print(f"\n🎬 Generating highlights for: {player_name}")
    print(f"📂 Demo: {demo_path}")
    print("=" * 70)
    
    # Parse demo
    print("\n📊 Step 1/3: Parsing demo...")
    parser = DemoParser(demo_path)
    events = parser.parse_player_events(player_name)
    
    if not events or not events.get("deaths"):
        print(f"❌ No events found for player: {player_name}")
        print("💡 Make sure the player name is spelled exactly as in-game (case-sensitive)")
        sys.exit(1)
    
    print(f"   ✅ Found {len(events['deaths'])} deaths, {len(events['kills'])} kills")
    
    # Analyze gameplay
    print("\n🔍 Step 2/3: Analyzing gameplay...")
    analyzer = GapAnalyzer(events)
    analysis = analyzer.analyze()
    print("   ✅ Analysis complete")
    
    # Identify highlights
    print("\n🎯 Step 3/3: Identifying key moments...")
    highlights_analyzer = HighlightsAnalyzer(events, analysis)
    highlights = highlights_analyzer.identify_highlights()
    print(f"   ✅ Found {len(highlights)} moments to review")
    
    # Create output directory
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    # Generate outputs
    demo_name = Path(demo_path).stem
    
    print("\n💾 Generating output files...")
    
    # 1. Review text file
    review_file = output_path / f"{demo_name}_highlights.txt"
    generate_review_file(highlights, str(review_file))
    print(f"   ✅ Review file: {review_file}")
    
    # 2. CS2 cfg script
    cfg_file = output_path / "highlights.cfg"
    generate_cs2_script(highlights, str(cfg_file), demo_name)
    print(f"   ✅ CS2 script: {cfg_file}")
    
    # 3. JSON data (for programmatic use)
    json_file = output_path / f"{demo_name}_highlights.json"
    with open(json_file, 'w', encoding='utf-8') as f:
        json.dump(highlights, f, indent=2, ensure_ascii=False)
    print(f"   ✅ JSON data: {json_file}")
    
    print("\n" + "=" * 70)
    print("✅ HIGHLIGHTS GENERATED SUCCESSFULLY!")
    print("=" * 70)
    print("\n📖 NEXT STEPS:")
    print(f"   1. Open the review file: {review_file}")
    print(f"   2. Copy highlights.cfg to your CS2 cfg folder:")
    print(f"      ~/.steam/steam/steamapps/common/Counter-Strike Global Offensive/game/csgo/cfg/")
    print(f"   3. Load demo in CS2: playdemo {demo_name}")
    print(f"   4. In console: exec highlights")
    print(f"   5. Press F5 to navigate through highlights")
    print("")
    print("💡 TIP: Use F6 for slow motion (0.5x) and F7 for normal speed")
    print("")


if __name__ == "__main__":
    main()
